name: Manifest check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Regenerate tools.json
        run: go run . --dump-tools
      - name: Fail if tools.json is stale
        run: git diff --exit-code tools.json
